/**
 * Market data cache schema for IndexedDB storage
 *
 * Caches historical return data from various API sources to reduce
 * API calls and enable offline access.
 */

/**
 * Supported financial data API sources
 */
export type ApiSource = 'fmp' | 'eodhd' | 'alphavantage' | 'tiingo' | 'yahoo';

/**
 * Single day's return data
 */
export interface DailyReturn {
  date: string; // YYYY-MM-DD format
  return: number; // Decimal return (e.g., 0.0123 for 1.23%)
}

/**
 * Cached market data record for IndexedDB storage
 */
export interface CachedMarketData {
  id?: number; // Auto-generated by Dexie
  symbol: string;
  source: ApiSource;
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  data: DailyReturn[];
  fetchedAt: string; // ISO date string
}
