/**
 * Portfolio schema for IndexedDB storage
 *
 * Stores user-created portfolios with their asset allocations.
 * Note: Dates stored as ISO strings for JSON serialization compatibility.
 */

import type { AssetClass } from '../../types/portfolio';

/**
 * Individual asset record within a portfolio
 */
export interface AssetRecord {
  id: string;
  symbol: string;
  name: string;
  assetClass: AssetClass;
  weight: number; // 0-1
}

/**
 * Portfolio record for IndexedDB storage
 */
export interface PortfolioRecord {
  id?: number; // Auto-generated by Dexie
  name: string;
  assets: AssetRecord[];
  created: string; // ISO date string
  modified: string; // ISO date string
  version: number; // For future schema migrations
}
